<?xml version="1.0"?>
<robot name="summit" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Se le han quitado las direcciones de atras, las texturas de las ruedas-->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="summit.gazebo" />
  <xacro:include filename="imu.xacro" /> 
<!--  <xacro:include filename="kinect.xacro" /> -->
  <xacro:include filename="rplidar.xacro" /> 

  <!-- Robot mechanical and motor parameters -->
  <xacro:property name="wheel_diameter" value="0.160"/>
  <xacro:property name="wheel_radius" value="0.080"/>
  <xacro:property name="wheel_mass" value="0.1"/>
  <xacro:property name="chassis_mass" value = "0.4"/>
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_offset_x" value="0.185" />    <!-- x,y,z in base_footprint CS -->
  <xacro:property name="wheel_offset_y" value="0.105" />
  <xacro:property name="wheel_offset_z" value="0.0" />
  <xacro:property name="steer_joint_effort_limit" value="100.0" />
  <xacro:property name="steer_joint_velocity_limit" value="3.0" />
  <xacro:property name="steer_joint_damping" value="0.2" />
  <xacro:property name="steer_joint_friction" value="0.1" />
  <xacro:property name="steer_mechanical_reduction" value="100.0" />
 
  <xacro:property name="wheel_joint_effort_limit" value="100.0" />
  <xacro:property name="wheel_joint_damping" value="0.0" />
  <xacro:property name="wheel_joint_friction" value="0.0" />

  <xacro:property name="wheel_joint_velocity_limit" value="200.0" />
  <xacro:property name="wheel_mechanical_reduction" value="1.0" />
  <xacro:property name="wheel_width" value="0.09" />
  <xacro:property name="ptz_joint_effort_limit" value="100.0" />
  <xacro:property name="ptz_joint_velocity_limit" value="100.0"/>
  <xacro:property name="ptz_joint_friction" value="0.1" />
  <xacro:property name="ptz_joint_damping" value="0.1" />
  <xacro:property name="ptz_mechanical_reduction" value="1.0" />

  <xacro:macro name="box_inertia" params="m x y z">
          <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(x*x+z*z)/12}" iyz = "0"
                    izz="${m*(x*x+z*z)/12}" /> 
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                    izz="${m*r*r/2}" /> 
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <xacro:cylinder_inertia m="${m}" r="${r}" h="${h}"/>
    </inertial>
  </xacro:macro>

  <!-- BASE FOOTPRINT -->

  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
             navigation stack depends on this frame -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
       <geometry>
	     <mesh filename="package://summit_deskribapena/meshes/summit_chassis.dae"/>
       </geometry>
    </visual>
    <collision>
       <geometry>
         <mesh filename="package://summit_deskribapena/meshes/summit_chassis.dae"/>
	     <!-- box size = "0.56 0.4 0.2"/ -->
       </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" x="0.56" y="0.4" z="0.2"/>
    </inertial>
  </link>

  <joint name="base_link_joint" type="fixed">
     <parent link="base_footprint"/>
     <child link="base_link"/>
     <origin rpy="0 0 0" xyz="0 0 ${(wheel_radius)}"/>
   </joint>

  <!-- BACK LEFT WHEEL -->
  <link name="back_left_wheel">
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>

    <visual>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
        <material name="grey">
             <color rgba="0.5 0.5 0.5 1"/>
        </material>
    </visual>
    <collision>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
    </collision>
  </link>

  <joint name="joint_back_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="-${wheel_offset_x} ${(wheel_offset_y + 0.060)} 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_joint_effort_limit}" velocity="${wheel_joint_velocity_limit}"/>
    <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}"/>
  </joint>

  <transmission name="joint_blw_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_back_left_wheel">
       <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
     </joint>
     <actuator name="joint_blw_motor">
	    <!-- hardwareInterface>VelocityJointInterface</hardwareInterface-->
        <mechanicalReduction>${wheel_mechanical_reduction}</mechanicalReduction>
     	<!--motorTorqueConstant>1</motorTorqueConstant-->
	 </actuator>
  </transmission>
  <!-- BACK RIGHT WHEEL -->
  <link name="back_right_wheel">
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>

    <visual>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
        <material name="grey">
                <color rgba="0.5 0.5 0.5 1"/>
        </material>
    </visual>
    <collision>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
    </collision>
  </link>

  <joint name="joint_back_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="-${wheel_offset_x} -${(wheel_offset_y + 0.060)} 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_joint_effort_limit}" velocity="${wheel_joint_velocity_limit}"/>
    <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}"/>
  </joint>

  <transmission name="joint_brw_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_back_right_wheel">
       <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
     </joint>
     <actuator name="joint_brw_motor">
	    <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>${wheel_mechanical_reduction}</mechanicalReduction>
     	<!-- motorTorqueConstant>1</motorTorqueConstant -->
	 </actuator>
  </transmission>

<!-- DIRECTION FORWARD LEFT      -->
<!-- =========================== -->

  <link name="front_left_wheel_dir">
    <visual>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="joint_front_left_wheel_dir" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_wheel_dir"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${steer_joint_effort_limit}" velocity="${steer_joint_velocity_limit}" lower="-0.7854" upper="0.7854"/>
    <joint_properties damping="${steer_joint_damping}" friction="{steer_joint_friction}"/>
  </joint>

  <transmission name="joint_flw_trans_dir">
	<type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_front_left_wheel_dir">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_flw_motor_dir">
	  <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>${steer_mechanical_reduction}</mechanicalReduction>
	  <!-- motorTorqueConstant>1</motorTorqueConstant -->
	</actuator>
  </transmission>

  <!-- FRONT LEFT WHEEL (GREY) -->
  <link name="front_left_wheel">
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>

    <visual>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
	<material name="gray">
		<color rgba="0.5 0.5 0.5 1"/>
      	</material>
    </visual>
    <collision>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
    </collision>
  </link>

  <joint name="joint_front_left_wheel" type="continuous">
    <parent link="front_left_wheel_dir"/>
    <child link="front_left_wheel"/>
    <origin xyz="0.0 0.060 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_joint_effort_limit}" velocity="${wheel_joint_velocity_limit}"/>
    <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}"/>
  </joint>

  <transmission name="joint_flw_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_front_left_wheel">
       <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
     </joint>
     <actuator name="joint_flw_motor">
	    <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>${wheel_mechanical_reduction}</mechanicalReduction>
     	<!-- motorTorqueConstant>1</motorTorqueConstant -->
	 </actuator>
  </transmission>


<!-- DIRECTION FORWARD RIGHT     -->
<!-- =========================== -->

  <link name="front_right_wheel_dir">
    <visual>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="5.1458e-5" iyy="5.1458e-5" izz="6.125e-5"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="joint_front_right_wheel_dir" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_wheel_dir"/>
    <origin xyz="${wheel_offset_x} -${wheel_offset_y} 0" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${steer_joint_effort_limit}" velocity="${steer_joint_velocity_limit}" lower="-0.7854" upper="0.7854"/>
    <joint_properties damping="${steer_joint_damping}" friction="{steer_joint_friction}"/>
  </joint>

  <transmission name="joint_frw_trans_dir">
	<type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_front_right_wheel_dir">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="joint_frw_motor_dir">
	  <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>${steer_mechanical_reduction}</mechanicalReduction>
	  <!-- motorTorqueConstant>1</motorTorqueConstant -->
	</actuator>
  </transmission>

  <!-- FRONT RIGHT WHEEL (GREY) -->
  <link name="front_right_wheel">
    <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>

    <visual>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
	<material name="grey">
		<color rgba="0.5 0.5 0.5 1"/>
      	</material>
    </visual>
    <collision>
       <geometry>
         <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
       </geometry>
    </collision>
  </link>

  <joint name="joint_front_right_wheel" type="continuous">
    <parent link="front_right_wheel_dir"/>
    <child link="front_right_wheel"/>
    <origin xyz="0.0 -0.060 0" rpy="${-pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="${wheel_joint_effort_limit}" velocity="${wheel_joint_velocity_limit}"/>
    <joint_properties damping="${wheel_joint_damping}" friction="{wheel_joint_friction}"/>
  </joint>

  <transmission name="joint_frw_trans">
	 <type>transmission_interface/SimpleTransmission</type>
     <joint name="joint_front_right_wheel">
       <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
     </joint>
     <actuator name="joint_frw_motor">
	    <hardwareInterface>VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>${wheel_mechanical_reduction}</mechanicalReduction>
     	<!-- motorTorqueConstant>1</motorTorqueConstant -->
	 </actuator>
  </transmission>
</robot>
